branch-defaults:
  master:
    environment: documentation
global:
  application_name: documentation
  branch: null
  default_ec2_keyname: null
  default_platform: docker
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: null
  workspace_type: Application
