version: 2
jobs:
  build-deploy-s3:
    docker:
      - image: circleci/ruby:2.6-stretch
    working_directory: ~/lumahealthhq/rest-service-docs
    steps:
    - checkout
    - run: sudo apt-get install -y nodejs awscli
    - run: sudo gem install bundler -v 1.15.4
    - run: bundle install
    - run: bundle exec middleman build --clean
    - run: aws s3 sync build/ s3://lumahealth-api-docs
workflows:
  version: 2
  main:
    jobs:
      - build-deploy-s3
          filters:
            branches:
              only:
                - master
                - dev
