version: 2.1

commands:
  install_deps:
    description: "Install necessary dependencies"
    steps:
    - run:
        name: "Installing dependencies"
        command: |
          sudo apt-get update && sudo apt-get install -y python-dev
          sudo curl -O https://bootstrap.pypa.io/get-pip.py
          sudo python get-pip.py
          sudo pip install awscli --upgrade
          sudo apt-get install -y dnsutils
          sudo pip install awsebcli --upgrade

  build_docs:
    description: "Build documentation"
    steps:
    - run:
        name: "Build Docs"
        command: |
          bundle install
          bundle exec middleman build --clean

jobs:
  deploy-to-stage:

    environment:
      ENVIRONMENT: 'stage'

    working_directory: ~/repo

    docker:
      - image: circleci/ruby:2.4.2-jessie-node

    steps:
      - checkout
      - install_deps
      - build_docs

      - setup_remote_docker  

      - run:
          name: "Build Container"
          command: docker build -t tier/documentation -f docker/Dockerfile .
      - run:
          name: "Push Container"
          command: |
            mkdir -p ~/.aws
            echo "[${ENVIRONMENT}]" > ~/.aws/credentials
            echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
            echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
            export ECR=075108987694.dkr.ecr.eu-central-1.amazonaws.com
            eval $(aws ecr get-login --region eu-central-1 --no-include-email)
            docker tag tier/documentation ${ECR}/tier/documentation
            docker push ${ECR}/tier/documentation:latest
      - run:
          name: "Deployment"
          command: |
            eb deploy documentation-stage
      - run:
          name: "Announce Deployment"
          command: ./.datadog/announce-deployment.sh

  deploy-to-production:

    environment:
      ENVIRONMENT: 'production'

    working_directory: ~/repo

    docker:
      - image: circleci/ruby:2.4.2-jessie-node

    steps:
      - checkout
      - install_deps
      - build_docs

      - setup_remote_docker  

      - run:
          name: "Build Container"
          command: docker build -t tier/documentation -f docker/Dockerfile .
      - run:
          name: "Push Container"
          command: |
            mkdir -p ~/.aws
            echo "[${ENVIRONMENT}]" > ~/.aws/credentials
            echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
            echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
            export ECR=373437620866.dkr.ecr.eu-central-1.amazonaws.com
            eval $(aws ecr get-login --region eu-central-1 --no-include-email)
            docker tag tier/documentation ${ECR}/tier/documentation
            docker push ${ECR}/tier/documentation:latest
      - run:
          name: "Deployment"
          command: |
            ### 
            #   Hack EB Deploy deploys what is checked in to HEAD
            #   We change the organisation ECR and stage it so eb deploy functions
            ### 
            sed -i s/075108987694/373437620866/g Dockerrun.aws.json
            git add Dockerrun.aws.json
            eb deploy documentation-production --staged
      - run:
          name: "DeploymentK8s"
          command: |
            mkdir -p ~/.aws
            echo "[${ENVIRONMENT}]" > ~/.aws/credentials
            echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
            echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
            aws eks update-kubeconfig --name tier-k8s-cluster
            helm upgrade --namespace ${ENVIRONMENT} --recreate-pods --install documentation ./k8s/documentation
      - run:
          name: "Announce Deployment"
          command: ./.datadog/announce-deployment.sh

workflows:
  version: 2
  deploy:
    jobs:
    - deploy-to-stage:
        context: global-staging
    - deploy-to-production:
        context: global-production
        requires:
          - deploy-to-stage
