ingress:
  enabled: true
  hosts:
    - host: documentation.tier-ops.com
      paths:
        - /
  tls:
    - secretName: documentation-tls-secret
      hosts:
      - documentation.tier-ops.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 1Gi
